music_rec/urls.py
from django.urls import path

from . import views

app_name = 'music_rec'
urlpatterns = [
    path('', views.index, name='index'),
    path('help', views.help, name='help'),
    path('error', views.error, name='error'),
    path('signup', views.signup, name='signup'),
    path('signup_success', views.signup_success, name='signup_success'),
    path('spotify_login', views.spotify_login, name='spotify_login'),
    path('spotify_success', views.spotify_success, name='spotify_success'),
    path('get_access_token', views.get_access_token, name='get_access_token'),
    path('expired_access_token', views.expired_access_token, name='expired_access_token'),
    path('user_login', views.user_login, name='user_login'),
    path('login_handler', views.login_handler, name='login_handler'),
    path('account', views.account, name='account'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('setup', views.setup, name='setup'),
    path('clear', views.clear, name='clear'),
    path('songs', views.songs, name='songs'),
    path('artists', views.artists, name='artists'),
    path('genres', views.genres, name='genres'),
    path('parameters', views.parameters, name='parameters'),
    path('submit', views.submit, name='submit'),
    path('playlist', views.playlist, name='playlist'),
]

spotify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_rec.urls'))
]

music_rec/models.py
from django.db import models
from django.contrib.auth.models import User

class SpotifyProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    refresh_token = models.CharField(max_length=255, null=True, blank=True)
    access_token = models.CharField(max_length=255, null=True, blank=True)
    userid = models.CharField(max_length=255, null=True, blank=True)

music_rec/forms.py
from django import forms

music_rec/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from .models import SpotifyProfile
from music_rec import api
import json
import logging
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
import requests

logger = logging.getLogger(__name__)

with open('secrets.json', 'r') as s:
    secret = json.load(s)
    CLIENT_ID = secret['client_id']
    CLIENT_SECRET = secret['client_secret']

# home page
def index(request):
    if str(request.user) != 'AnonymousUser':
        context = {'user': 'logged in as ' + str(request.user)}
    else:
        context = {'user': 'No User Logged in'} 
    return render(request, 'music_rec/index.html', context)

# help page with instructions
def help(request):
    return render(request, 'music_rec/help.html')

def error(request):
    if request.POST:
        logger.warning(request.POST['error'])
        response = HttpResponse()
        return response
    else:
        logger.warning('did not send a post request to error')
        response = HttpResponse()
        response.status_code = 300
        return response

#signup for an account and link your spotify account
def signup(request):
    return render(request, 'music_rec/signup.html')

# handler for linking spotify account and storing credentials in db
def signup_success(request):
    if request.POST:
        # Create an instance of EmailValidator
        email_validator = EmailValidator()

        try:
            # Call the __call__ method of EmailValidator to validate the email
            email_validator(request.POST['email'])
        except ValidationError:
            return render(request, 'music_rec/signup.html', {'error':'Enter a valid email address.'})
        # ensure password is at least 8 characters
        if len(request.POST['password']) < 8:
            return render(request, 'music_rec/signup.html', {'error': 'Enter a password with at least 8 characters.'})
        # ensure passwords match
        elif request.POST['password'] != request.POST['confirm_password']:
            return render(request, 'music_rec/signup.html', {'error': 'Enter matching passwords.'})
        # if all conditions are met create a new user with the credentials
        else:
            user = User.objects.create_user(username=request.POST['email'],
                                            email=request.POST['email'],
                                            password=request.POST['password'])
            user.save()
            # associate the newly created profile with the spotify profile object in a 1 to 1 relationship
            SpotifyProfile.objects.create(user=user)
            login(request, user)
            auth_url = api.get_refresh_token()
            return HttpResponseRedirect(auth_url.auth_url)

@login_required(login_url='/user_login')
def spotify_login(request):
    auth_url = api.get_refresh_token()
    return HttpResponseRedirect(auth_url.auth_url)

# page that is displayed after successfully logging in
@login_required(login_url='/user_login')
def spotify_success(request):
    # get the spotify profile of current logged in user
    spotify_profile = SpotifyProfile.objects.get(user=request.user)

    # sets refresh and access token to spotify profile model
    tokens = api.get_access_token(request.GET['code'])
    spotify_profile.access_token = tokens.access_token
    spotify_profile.refresh_token = tokens.refresh_token

    # get the userid of the user and associate it to the spotify profile model
    spotify_profile.userid = api.get_userid(spotify_profile.access_token).userid
    spotify_profile.save()

    return render(request, 'music_rec/spotify_success.html')

# get the access token from the database for a logged in user
@login_required(login_url='/user_login')
def get_access_token(request):
    return JsonResponse({'access': SpotifyProfile.objects.get(user=request.user).access_token})

# get a new access token if it is expired
@login_required(login_url='/user_login')
def expired_access_token(request):
    spotify_profile = SpotifyProfile.objects.get(user=request.user)
    spotify_profile.access_token = api.expired_access_token(spotify_profile.refresh_token).access_token
    spotify_profile.save()
    return JsonResponse({'success': 'success'})

# page to log into an existing user's account
def user_login(request):
    return render(request, 'music_rec/user_login.html')

# handle log in of an existing user
# TODO do not yet have a password reset
def login_handler(request):
    if request.POST:
        user = authenticate(username=request.POST['email'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return render(request, 'music_rec/login_success.html')
    else:
        return render(request, 'music_rec/user_login.html', {'error': 'Enter a valid login'})

# manage account and connect spotify account
@login_required(login_url='/user_login')
def account(request):
    try:
        if SpotifyProfile.objects.get(user=request.user).userid != None:
            spotify_account = SpotifyProfile.objects.get(user=request.user).userid
            need_to_connect_spotify = False
        else:
            spotify_account = 'No Spotify Account Connected'
            need_to_connect_spotify = True
    except Exception:
        SpotifyProfile.objects.create(user=request.user)
        spotify_account = 'No Spotify Account Connected'
        need_to_connect_spotify = True
    context = {'username': request.user, 'spotify': spotify_account, 'need_to_connect_spotify': need_to_connect_spotify}
    return render(request, 'music_rec/account.html', context)

# log out a logged in user
def user_logout(request):
    logout(request)
    return render(request, 'music_rec/index.html')

# main page to see what items have been added to each list
@login_required(login_url='/user_login')
def setup(request):
    # session variables store song artsit and genres selection information
    if 'songs' not in request.session:
        request.session['songs'] = []
    if 'artists' not in request.session:
        request.session['artists'] = []
    if 'genres' not in request.session:
        request.session['genres'] = []
    if 'songs_ids' not in request.session:
        request.session['songs_ids'] = []
    if 'artists_ids' not in request.session:
        request.session['artists_ids'] = []
    if 'genres_ids' not in request.session:
        request.session['genres_ids'] = []

    if request.POST:
        data = request.POST.copy()

        # collect data from form and add it to appropriate session variables for items
        for item in data:
            if request.META.get('HTTP_REFERER').endswith(reverse('music_rec:songs')) and item != 'csrfmiddlewaretoken' and len(request.session['songs']) < 5:
                request.session['songs'] = request.session['songs'] + [item]
                request.session['songs_ids'] = request.session['songs_ids'] + [data[item]]
            
            elif request.META.get('HTTP_REFERER').endswith(reverse('music_rec:artists')) and item != 'csrfmiddlewaretoken' and len(request.session['artists']) < 5:
                request.session['artists'] = request.session['artists'] + [item]
                request.session['artists_ids'] = request.session['artists_ids'] + [data[item]]
            
            elif request.META.get('HTTP_REFERER').endswith(reverse('music_rec:genres')) and item != 'csrfmiddlewaretoken' and len(request.session['genres']) < 5:
                request.session['genres'] = request.session['genres'] + [item]
                request.session['genres_ids'] = request.session['genres_ids'] + [data[item]]
    
    context = {'songs': request.session['songs'],
               'genres': request.session['genres'],
               'artists': request.session['artists']}
    return render(request, 'music_rec/setup.html', context)

# clear all songs artists and genres from session variables
def clear(request):
    try:
        request.session['songs'] = []
        request.session['artists'] = []
        request.session['genres'] = []
        request.session['songs_ids'] = []
        request.session['artists_ids'] = []
        request.session['genres_ids'] = []
    except Exception as e:
        logger.warning(e)
    
    return render(request, 'music_rec/setup.html')

# method that checks a user has a refresh token
def spotify_account_check(user):
    return SpotifyProfile.objects.get(user=user).refresh_token != None

# search for songs
@user_passes_test(spotify_account_check, login_url='/spotify_login')
def songs(request):
    return render(request, 'music_rec/songs.html')

# search for artists
@user_passes_test(spotify_account_check, login_url='/spotify_login')
def artists(request):
    return render(request, 'music_rec/artists.html')

# search for genres
@user_passes_test(spotify_account_check, login_url='/spotify_login')
def genres(request):
    return render(request, 'music_rec/genres.html')

# enter extra parameters if wanted for recommendations algorithm
def parameters(request):
    context = {}
    return render(request, 'music_rec/parameters.html', context)

# view songs returned and name playlist
@login_required(login_url='/user_login')
def submit(request):
    parameters={}

    # collect form data
    if request.POST:
        data = request.POST.copy()
        del data['csrfmiddlewaretoken']
        for key,value in data.items():
            parameters[key]=float(value)
            if key=="target_popularity":
                parameters[key]=int(value)
    try:
        payload=[]
        uris=[]
        # make api call to get songs from recommendation algorithm

music_rec/templates/music_rec/account.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/account.css' %}">
    </head>
    <body>
        <h1>Spotify Music Discovery</h1>
        <h2>Username: {{ username }}</h3>
        <h2>Spotify Account: {{ spotify }}</h3>
        {% if need_to_connect_spotify == True %}
            <button name="spotify_login" onclick="window.location.href='{% url 'music_rec:spotify_login' %}';">Connect your Spotify Account</button>
        {% endif %}
        <button name="back" onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
    </body>
</html>

music_rec/templates/music_rec/artists.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/artists.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <h1>Enter an Artist to add</h1>
    <div class="search">
        <input type="text" id="search" placeholder="search for your favorite Spotify artists"></input>
        <button class="search-button" onclick="getArtists()">search</button>
    </div>
    <form action="{% url 'music_rec:setup' %}" method="post">
        {% csrf_token %}
        <div id="artists"></div>
        {% block js_block %}
	        <script type="text/javascript" src="{% static 'music_rec/artists.js' %}"></script> 
        {% endblock %}
        <div class="submit">
            <button id="submit-button" class="submit-button">Add to List</button>
        </div>
    </form>
    <button class="back" onclick="window.location.href='{% url 'music_rec:setup' %}';">Back</button>
</html>

music_rec/templates/music_rec/genres.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/genres.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <h1>Select up to 5 genres to add</h1>
    <form action="{% url 'music_rec:setup' %}" method="post">
        {% csrf_token %}
        <div id="genres" class="genres"></div>
        {% block js_block %}
	        <script type="text/javascript" src="{% static 'music_rec/genres.js' %}"></script>
        {% endblock %}
        <button class="submit" id="submit-button">Add to List</button>
    </form>
    <button class="back" onclick="window.location.href='{% url 'music_rec:setup' %}';">Back</button>
</html>

music_rec/templates/music_rec/help.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/help.css' %}">
    </head>
    <body>
        <h1>Spotify Music Discovery</h1>
        <h3>1. Signup</h3>
        <p>Click the button to signup and create an account. After you create an account you will be prompted to sign into your spotify account to link it with your website account.</p>
        <img src="{% static 'music_rec/signup.png' %}" alt="Signup Page" style="width:75%;height:10%;">
        
        <h3>2. Enter up to 5 songs, 5 artists, and  5 genres</h3>
        <p>Click Get Music Recommendations to enter up to 5 songs, 5 artists, and 5 genres that you want to base the music recommendations on. You can enter as many or as few as you want and when you are ready click continue.</p>
        <img src="{% static 'music_rec/setup.png' %}" alt="Setup Page" style="width:75%;height:10%;">

        <p>After clicking on songs or artists you can search for any song or artist you want. Click on the song or artists you want and click the add to list button to add them to the list of items to get recommendations on<p>
            <img src="{% static 'music_rec/song_search.png' %}" alt="Song Search Page" style="width:75%;height:10%;">
        <p>After clicking on genres click up to 5 genres to add to the list of items to get recommendations on.</p>
        <img src="{% static 'music_rec/genres.png' %}" alt="Genres search Page" style="width:75%;height:10%;">
        
        <h3>3. Enter parameters or continue without them</H3>
        <p>Adjust the sliders and click continue or click continue without parameters to continue without having the sliders effect the song recommendations you choose. Enter a number between 1 - 100 songs to be reccomended</p>
        <img src="{% static 'music_rec/parameters.png' %}" alt="Parameters Page" style="width:75%;height:10%;">

        <h3>4. Name the Playlist and add it to your Spotify account</h3>
        <p>You can see the the songs and artists Spotify has suggested based on your inputs and can now name the playlist and add it to your Spotify account.</p>
        <img src="{% static 'music_rec/playlist.png' %}" alt="Playlist Creation Page" style="width:75%;height:10%;">

        <p></p>
        <button onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
    </body>
</html>

music_rec/templates/music_rec/index.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/index.css' %}">
    </head>
    <body>
        <h1>Spotify Music Discovery</h1>
        <h2>{{ user }}</h2>
        <button name="login" onclick="window.location.href='{% url 'music_rec:user_login' %}';">Login</button>
        <br>
        <button onclick="window.location.href='{% url 'music_rec:signup' %}';">Signup</button>
        <br>
        <button name="setup" onclick="window.location.href='{% url 'music_rec:setup' %}';">Get Music Recommendations</button>
        <br>
        {% if user != 'No User Logged in' %}
            <button name="account" onclick="window.location.href='{% url 'music_rec:account' %}';">Account</button>
            <br>
            <button name="logout" onclick="window.location.href='{% url 'music_rec:user_logout' %}';">Logout</button>
            <br>
        {% endif %}
        <button name="help" onclick="window.location.href='{% url 'music_rec:help' %}';">Help</button>
    </body>
</html>

music_rec/templates/music_rec/login_success.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Success</title>
        <link rel="stylesheet" href="{% static 'music_rec/login_success.css' %}">
    </head>
    <body>
        <h1>Success</h1>
        <button id="back" onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
    </body>
</html>

music_rec/templates/music_rec/parameters.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/parameters.css' %}">
    </head>
    <body>
        <form action="{% url 'music_rec:submit' %}" method="post">
            {% csrf_token %}
            <div class="parameters">
                <label>Acousticness</label>
                <input type="range" name="target_acousticness" min="0" max="1" step="0.01"></input>
                <label>Danceability</label>
                <input type="range" name="target_danceability" min="0" max="1" step="0.01"></input>
                <label>Energy</label>
                <input type="range" name="target_energy" min="0" max="1" step="0.01"></input>
                <label>Instrumentalness</label>
                <input type="range" name="target_instrumentalness" min="0" max="1" step="0.01"></input>
                <label>Liveness</label>
                <input type="range" name="target_liveness" min="0" max="1" step="0.01"></input>
                <label>Loudness</label>
                <input type="range" name="target_loudness" min="0" max="1" step="0.01"></input>
                <label>Popularity</label>
                <input type="range" name="target_popularity" min="0" max="100"></input>
                <label>Speechiness</label>
                <input type="range" name="target_speechiness" min="0" max="1" step="0.01"></input>
                <label>Tempo</label>
                <input type="range" name="target_tempo" min="0" max="1" step="0.01"></input>
                <label>Valence</label>
                <input type="range" name="target_valence" min="0" max="1" step="0.01"></input>
                <button id="submit-button">Submit Parameters</button>
            </div>
        </form>
        <div class="back">
            <button onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
        </div>
        <button onclick="window.location.href='{% url 'music_rec:submit' %}';">Continue without Parameters</button>
    </body>
</html>

music_rec/templates/music_rec/playlist.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/playlist.css' %}">
    </head>
    <body>
        <h1>{{ response }}</h1>
    </body>
    <button class="continue" onclick="window.location.href='{% url 'music_rec:setup' %}';">Return to Setup</button>
</html>

music_rec/templates/music_rec/setup.html
<!DOCTYPE html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/setup.css' %}">
    </head>
    <body>
        <div class="song-container">
          <button id="songs" onclick="window.location.href='{% url 'music_rec:songs' %}';">Songs</button>
          {% for song in songs %}
          <label class="song-element">{{song}}</label>
          {% endfor %}
          <button class="bottom-button" onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
        </div>
        <div class="artist-container">
          <button id="artists" onclick="window.location.href='{% url 'music_rec:artists' %}';">Artists</button>
          {% for artist in artists %}
          <label class="artist-element">{{artist}}</label>
          {% endfor %}
          <button class="bottom-button" id="submit" onclick="window.location.href='{% url 'music_rec:parameters' %}';">Continue</button>
        </div>
        <div class="genre-container">
          <button id="genres" onclick="window.location.href='{% url 'music_rec:genres' %}';">Genres</button>
          {% for genre in genres %}
          <label class="genre-element">{{genre}}</label>
          {% endfor %}
          <button class="bottom-button" onclick="window.location.href='{% url 'music_rec:clear' %}';">Clear</button>
        </div>
      </body>
</html>

music_rec/templates/music_rec/signup.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/signup.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="box1">
                <p>Enter your email and a password that is at least 8 characters long</p>
            </div>
            <div class="box2">
                <form action="{% url 'music_rec:signup_success' %}" method="post">
                    {% csrf_token %}
                    <label>Email</label>
                    <input type="text" name="email"></input>
                    <br>
                    <label>Password</label>
                    <input type="password" name ="password"></input>
                    <br>
                    <label>Confirm Password</label>
                    <input type="password" name = "confirm_password"></input>
                    <br>
                    <button id="submit-button">Signup</button>    
                </form>
            </div>
            <div class="box3">
                {% if error %}
                    <label>{{error}}</label>
                {% endif %}
            </div>
        </div>
    </body>
    <button class="back" onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
</html>

music_rec/templates/music_rec/songs.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/songs.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
    <h1>Enter a Song to search</h1>
    <div class="search">
        <input type="text" id="search" placeholder="search for your favorite Spotify songs"></input>
        <button class="search-button" onclick="getSongs()">search</button>
    </div>
    <form action="{% url 'music_rec:setup' %}" method="post">
        {% csrf_token %}
        <div id="songs"></div>
        {% block js_block %}
            <script type="text/javascript" src="{% static 'music_rec/songs.js' %}"></script> 
        {% endblock %}
        <div class="submit">
            <button id="submit-button" class="submit-button">Add to List</button>
        </div>
    </form>
    
    <button class="back" onclick="window.location.href='{% url 'music_rec:setup' %}';">Back</button>
</html>

music_rec/templates/music_rec/spotify_success.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Login Success</title>
        <link rel="stylesheet" href="{% static 'music_rec/spotify_success.css' %}">
    </head>
    <h1>Success</h1>
    <button id="back" onclick="window.location.href='{% url 'music_rec:index' %}';">Return to Home</button>
</html>

music_rec/templates/music_rec/submit.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Recommendations</title>
        <link rel="stylesheet" href="{% static 'music_rec/submit.css' %}">
    </head>
    <body>
        <h1>Recommendations</h1>
        <h1>Submit/Modify:</h1>
        <table class="song-table">
             <thead>
                 <tr>
                     <th>Artist</th>
                     <th>Song</th>
                 </tr>
             </thead>    
             <tbody>
                 {% for song in recommendations%}
                 <tr>
                     {% for element in song%}
                     <td>{{element}}</td>
                     {% endfor %}
                 </tr>
                {% endfor %}
             </tbody>
        </table>
        <form action="{% url 'music_rec:playlist' %}" method="post">
            {% csrf_token %}
            <label>Playlist Name</label>
            <input type="text" name="playlist"></input>
            <button id="submit-button">Create Playlist</button>
        </form>
        <button onclick="window.location.href='{% url 'music_rec:index' %}';">Return to Home</button>
    </body>
</html>

music_rec/templates/music_rec/user_login.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <title>Spotify Music Discovery</title>
        <link rel="stylesheet" href="{% static 'music_rec/user_login.css' %}">
    </head>
    <body>
        <h2>{{ error }}</h2>
        <form action="{% url 'music_rec:login_handler' %}" method="post">
            {% csrf_token %}
            <label>Email</label>
            <input type="text" name="email"></input>
            <br>
            <label>Password</label>
            <input type="password" name="password"></input>
            <br>
            <button id="submit-button">Log in</button>
        </form>
    </body>
    <button class="back" onclick="window.location.href='{% url 'music_rec:index' %}';">Back</button>
</html>